import {expect,it} from 'vitest';
import {fighter,simulate} from './engine';
import {resourcePredictions,combatCard} from './combatCards';
import {COMBAT_FIXTURES} from './combatFixtures';
const idle=()=>fighter('B',['healing-seed']);
it('Triggers arm only after completion and become available again next tick',()=>{const a=fighter('A',['healing-seed','backdraft','spark']);a.health=100;const r=simulate(a,idle());expect(r.frames[1].notices?.filter(n=>n.status==='trigger')).toHaveLength(0);expect(r.frames[2].notices?.filter(n=>n.status==='trigger')).toHaveLength(1);expect(r.frames[3].notices?.filter(n=>n.status==='trigger')).toHaveLength(2);});
it('Echo Triggers cannot fire before their card arms',()=>{const a=fighter('A',['storm']);a.statuses.tide=3;const r=simulate(a,idle());expect(r.frames[1].notices?.some(n=>n.status==='trigger')).toBe(false);const later=r.frames.find(f=>f.notices?.some(n=>n.status==='trigger'));expect(later).toBeDefined();expect(later!.tick).toBeGreaterThan(1);});
it('Whirlpool records both its own slot and the last Trigger slot',()=>{const a=fighter('A',['healing-seed','spark','whirlpool']);a.health=100;const r=simulate(a,idle());expect(r.frames[1].notices?.some(n=>n.status==='retrigger')).toBe(false);expect(r.frames[3].notices?.find(n=>n.status==='retrigger')).toMatchObject({index:2,targetIndex:0});});
it('Awaken tracks copies independently and transforms after a completed Echo',()=>{const a=fighter('A',['deep-water','deep-water']);a.statuses.tide=3;const r=simulate(a,idle());expect(r.frames[1].player.memory.cards?.[0].awakened).toBe(true);expect(r.frames[1].player.memory.cards?.[1]?.awakened).not.toBe(true);expect(r.frames[1].bot.health).toBe(410);expect(r.frames[1].notices?.filter(n=>n.status==='awaken')).toHaveLength(1);expect(r.frames.flatMap(f=>f.notices??[]).filter(n=>n.status==='awaken'&&n.index===0)).toHaveLength(1);});
it('Heat consumption Awakens Conflagrate, while free activations do not count as consumption',()=>{const a=fighter('A',['scorch','conflagrate'],[],[0,3]);a.statuses.heat=5;const r=simulate(a,idle());expect(r.frames[1].player.memory.heatConsumed).toBe(1);expect(r.frames[1].player.memory.cards?.[1].awakened).toBe(true);expect(r.frames[2].player.memory.heatConsumed).toBe(1);});
it('Ocean Heart and Tidal Power change future activations permanently without stacking recasts',()=>{const a=fighter('A',['ocean-heart','tidal-power','jet'],[],[3,3,0]);const r=simulate(a,idle());expect(r.frames[2].player.memory.rules).toMatchObject({tideThreshold:2,echoPower:1.5,echoRetrigger:1});expect(r.frames.some(f=>f.events.some(e=>e.side==='player'&&e.details?.includes('Echo 150%')))).toBe(true);});
it('Poison events Awaken Venom Bloom; blocked events do not count',()=>{const a=fighter('A',['venom-bloom'],[],[3]);const r=simulate(a,idle());expect(r.frames[4].player.memory.cards?.[0].awakened).toBe(true);const b=idle();b.statuses.guard=20;expect(simulate(a,b).frames[4].player.memory.cards?.[0]?.awakened).not.toBe(true);});
it('predictions mark only the next eligible cards from currently held counters',()=>{const a=fighter('A',['holy-light','jet','pyroblast']);a.statuses={heat:5,tide:3};expect(resourcePredictions(a)).toEqual({heat:1,tide:1});});
it.each(Object.entries(COMBAT_FIXTURES))('%s full builds are deterministic, symmetric and bounded',(_,preset)=>{const a=fighter('A',[...preset.player],[],preset.player.map(()=>3),[],5),b=fighter('B',[...preset.bot],[],preset.bot.map(()=>3),[],5);const r=simulate(a,b),swap=simulate(b,a);expect(r).toEqual(simulate(a,b));expect(r.frames.at(-1)?.player.health).toBe(swap.frames.at(-1)?.bot.health);expect(r.frames.at(-1)?.bot.health).toBe(swap.frames.at(-1)?.player.health);expect(r.frames.at(-1)!.tick).toBeLessThanOrEqual(30);});

it('Echo-only Tide and Slow payoffs grant the printed whole charge once',()=>{const a=fighter('A',['brine']);a.statuses.tide=3;expect(simulate(a,idle()).frames[3].player.statuses.tide).toBe(2);const b=fighter('A',['tsunami'],[],[3]);b.statuses.tide=3;expect(simulate(b,idle()).frames[2].bot.statuses.slow).toBe(5);});

it('Awakened Venom Bloom still displays its Poison application',()=>{const a=fighter('A',['venom-bloom'],[],[3]);const f=simulate(a,idle()).frames[4].player;expect(combatCard(f,0).rules).toContain('Apply Poison for 5 ticks');expect(combatCard(f,0).rules).toContain('100% more damage');});
