import {expect,it} from 'vitest';
import {fighter,simulate} from './engine';
import {COMBAT_FIXTURES} from './combatFixtures';
const preview=(name:keyof typeof COMBAT_FIXTURES)=>{const p=COMBAT_FIXTURES[name];return simulate(fighter('A',[...p.player],[],p.player.map(()=>3),[],5),fighter('B',[...p.bot],[],p.bot.map(()=>3),[],5));};
it('records the damaged Imp as the origin of Imp Hurt triggers',()=>{const defender=fighter('B',['soulbound']);defender.imp={health:200,maxHealth:200,guard:0};defender.memory.cards={0:{armed:true}};const notices=simulate(fighter('A',['spark']),defender).frames[1].notices??[];expect(notices.find(n=>n.status==='trigger'&&n.side==='bot'&&n.index===0)?.origin).toEqual({side:'bot',kind:'imp'});});
it('records the spell consuming Heat and the card receiving its Retrigger separately',()=>{const notices=preview('fire').frames.flatMap(f=>f.notices??[]);const heat=notices.find(n=>n.status==='trigger'&&n.side==='player'&&n.index===2);expect(heat?.origin).toMatchObject({side:'player',kind:'spell'});expect(heat?.origin?.index).not.toBe(2);const a=fighter('A',['healing-seed','spark','whirlpool']);a.health=100;const repeat=simulate(a,fighter('B',['prayer'])).frames[3].notices?.find(n=>n.status==='retrigger');expect(repeat).toMatchObject({index:2,targetIndex:0,origin:{side:'player',kind:'spell',index:2}});});
it('Poison triggers originate at the damaged opponent and fatal triggers at their owner',()=>{const a=fighter('A',['bramble-wall']);const b=fighter('B',['healing-seed']);b.statuses.poison=10;const poison=simulate(a,b).frames.flatMap(f=>f.notices??[]).find(n=>n.status==='trigger');expect(poison?.origin).toEqual({side:'bot',kind:'wizard'});const c=fighter('A',['divine-intervention','healing-seed'],[],[3,0]);c.health=20;const fatal=simulate(c,fighter('B',['healing-seed','pyroblast'])).frames.flatMap(f=>f.notices??[]).find(n=>n.status==='trigger');expect(fatal?.origin).toEqual({side:'player',kind:'wizard'});});
it('every Trigger and Retrigger has a valid visual origin',()=>{for(const key of Object.keys(COMBAT_FIXTURES) as (keyof typeof COMBAT_FIXTURES)[])for(const frame of preview(key).frames)for(const n of frame.notices??[])if(n.status==='trigger'||n.status==='retrigger'){expect(n.origin).toBeDefined();if(n.origin?.kind==='spell')expect(n.origin.index).toBeGreaterThanOrEqual(0);}});

it('preserves the full Tide threshold in feedback before it is consumed',()=>{const a=fighter('A',['current','storm'],[],[3,0]);const r=simulate(a,fighter('B',['healing-seed']));expect(r.frames[1].player.statuses.tide).toBe(3);expect(r.frames[2].notices?.find(n=>n.status==='tide')?.resource).toEqual({before:3,spent:3,after:0});});
it('resource feedback retains excess stacks and reports free Heat honestly',()=>{const a=fighter('A',['scorch','spark']);a.statuses.heat=10;const r=simulate(a,fighter('B',['healing-seed']));expect(r.frames[1].notices?.find(n=>n.status==='heat')?.resource).toEqual({before:10,spent:5,after:5});expect(r.frames[2].notices?.find(n=>n.status==='heat')?.resource).toEqual({before:6,spent:0,after:6});});
