const { SPELLS, AUGMENTS } = require('./game.cjs');
function report(data, baseline) {
  const payload = JSON.stringify({ data, baseline, names: Object.fromEntries([...Object.values(SPELLS), ...Object.values(AUGMENTS)].map(x => [x.id, x.name])) }).replace(/</g, '\\u003c');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wizard Balance Lab</title>
<style>body{font:15px system-ui;background:#101522;color:#e9eefb;margin:0;padding:32px;max-width:1500px;margin:auto}h1{font-size:34px}h2{font-size:21px}p{color:#b4c2da;line-height:1.6}select{padding:9px;background:#242e44;color:white;border:1px solid #586981;border-radius:6px}section{background:#192237;padding:24px;border-radius:12px;margin:20px 0;overflow:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(450px,1fr));gap:20px}.grid section{margin:0}table{border-collapse:collapse;width:100%}td,th{padding:9px;border-bottom:1px solid #35415a;text-align:left;font-size:13px}.bar{height:14px;background:#70b7ff;border-radius:3px;min-width:1px}pre{white-space:pre-wrap;font-size:12px}summary{cursor:pointer;padding:8px}small{color:#b4c2da}</style>
<h1>Wizard Balance Lab</h1><p id="meta"></p><p>Exploratory evidence, not a balance verdict. Score = wins + half of draws. Samples are correlated build matchups, not independent human players. Spell and pair charts show association, not causation. Economy augments need progression testing.</p>
<label>Experiment <select id="mode"><option value="arena">Controlled arena</option><option value="progression">Bot progression</option><option value="search">Search · held-out opponents</option></select></label>
<label> Level <select id="stage"><option value="all">All levels</option></select></label>
<p id="summary"></p><div class="grid"><section><h2>Spell score and appearances</h2><div id="spells"></div></section><section><h2>Augment score and appearances</h2><div id="augments"></div></section></div>
<section><h2>Domain matchup heatmap</h2><div id="heat"></div></section>
<div class="grid"><section><h2>Battle duration</h2><div id="duration"></div></section><section><h2>Remaining health · fraction of starting health</h2><div id="health"></div></section><section><h2>Spell pair associations · top 25</h2><div id="pairs"></div></section><section><h2>Paired augment removal · combat score lift</h2><p>Positive means adding the augment helped against the same opponents. Based on controlled arena only; this does not measure shop value.</p><div id="lift"></div></section></div>
<section><h2>Progression by round</h2><div id="rounds"></div></section><section><h2>Compared with previous report</h2><div id="compare"></div></section>
<section><h2>Builds to investigate</h2><p>Exact casting order, acquisition ages, upgrades, and augments are saved below. Search candidates are evaluated against opponents excluded from their training.</p><div id="builds"></div></section>
<script>const {data,baseline,names}=${payload};
const el=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=n=>(n*100).toFixed(1)+'%';
const index=Object.fromEntries(data.builds.map(b=>[b.id,b]));
el('meta').textContent='Seed '+data.options.seed+' · '+data.matches.length+' recorded battles · '+data.elapsedSeconds+' seconds · rules '+data.fingerprint.slice(0,12);
[...new Set(data.builds.map(b=>b.stage))].sort((a,b)=>a-b).forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=n;el('stage').append(o)});
function table(headers,rows){return '<table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function chart(target, entries, signed=false){el(target).innerHTML=table(['Item',signed?'Lift':'Value','Samples'],entries.map(([name,value,n])=>[esc(names[name]||name),'<div style="min-width:140px">'+pct(value)+'<div class="bar" style="width:'+Math.min(100,Math.abs(value)*100)+'%;background:'+(value<0?'#f89494':'#70b7ff')+'"></div></div>',n]));}
function summarize(matches,buildIndex,key){const map={};for(const m of matches)for(const [id,s] of [[m.a,m.score],[m.b,1-m.score]]) {const b=buildIndex[id];let keys=key==='id'?[id]:[...new Set(b[key])];if(key==='pairs'){const d=[...new Set(b.deck)].sort();keys=[];for(let i=0;i<d.length;i++)for(let j=i+1;j<d.length;j++)keys.push((names[d[i]]||d[i])+' + '+(names[d[j]]||d[j]));}for(const k of keys){const v=map[k]??=[0,0];v[0]+=s;v[1]++}}return Object.entries(map).map(([k,[s,n]])=>[k,s/n,n]).sort((a,b)=>b[1]-a[1]||b[2]-a[2]);}
function render(){const mode=el('mode').value, stage=el('stage').value;const ms=data.matches.filter(m=>m.mode===mode&&(stage==='all'||m.stage===+stage));
el('summary').textContent=ms.length+' battles · '+ms.filter(m=>m.score===.5).length+' draws · '+ms.filter(m=>m.endReason==='timeout').length+' timeouts';
chart('spells',summarize(ms,index,'deck'));chart('augments',summarize(ms,index,'augments'));chart('pairs',summarize(ms,index,'pairs').slice(0,25));
const durations={},health={},cells={};for(const m of ms){durations[m.ticks]=(durations[m.ticks]||0)+1;for(const [id,h] of [[m.a,m.healthA],[m.b,m.healthB]]){const b=index[id],max=data.rules.health+(b.level-1)*data.rules.healthPerLevel-(b.augments.includes('glass-cannon')?125:0);const bucket=Math.min(9,Math.max(0,Math.floor(h/max*10)));health[bucket]=(health[bucket]||0)+1;}for(const [a,b,s] of [[m.a,m.b,m.score],[m.b,m.a,1-m.score]]){const k=index[a].profile+'|'+index[b].profile;const c=cells[k]??=[0,0];c[0]+=s;c[1]++}}
chart('duration',Object.entries(durations).sort((a,b)=>+a[0]-+b[0]).map(([k,n])=>[k+' ticks',n/(ms.length||1),n]));chart('health',Object.entries(health).sort((a,b)=>+a[0]-+b[0]).map(([k,n])=>[(+k*10)+'–'+(+k*10+10)+'%',n/(2*ms.length||1),n]));
const profiles=[...new Set(ms.flatMap(m=>[index[m.a].profile,index[m.b].profile]))].sort();el('heat').innerHTML=table(['Build / opponent',...profiles],profiles.map(a=>[esc(a),...profiles.map(b=>{const c=cells[a+'|'+b];return c?'<span style="display:block;padding:8px;background:hsl('+(c[0]/c[1]*125)+',40%,28%)">'+pct(c[0]/c[1])+' · n='+c[1]+'</span>':'—'})]));
const lift={};for(const c of data.contributions.filter(c=>stage==='all'||c.stage===+stage)){const v=lift[c.augment]??=[0,0];v[0]+=c.delta;v[1]++}chart('lift',Object.entries(lift).map(([k,[s,n]])=>[k,s/n,n]).sort((a,b)=>b[1]-a[1]),true);
const rounds={};for(const m of data.matches.filter(m=>m.mode==='progression')){const v=rounds[m.round]??=[0,0,0];v[0]+=m.ticks;v[1]+=m.score===.5?1:0;v[2]++}el('rounds').innerHTML=table(['Round','Mean duration','Draw rate','Battles'],Object.entries(rounds).map(([k,v])=>[k,(v[0]/v[2]).toFixed(1),pct(v[1]/v[2]),v[2]]));
if(baseline){const bi=Object.fromEntries(baseline.builds.map(b=>[b.id,b]));const prev=Object.fromEntries(summarize(baseline.matches.filter(m=>m.mode===mode&&(stage==='all'||m.stage===+stage)),bi,'deck').map(x=>[x[0],x]));chart('compare',summarize(ms,index,'deck').filter(x=>prev[x[0]]).map(([k,s,n])=>[k,s-prev[k][1],n]),true);}else el('compare').textContent='Supply --baseline path/to/results.json to compare a previous run.';
el('builds').innerHTML=summarize(ms,index,'id').slice(0,20).map(([id,s,n])=>'<details><summary>'+esc(id)+' · '+pct(s)+' · n='+n+'</summary><pre>'+esc(JSON.stringify(index[id],null,2))+'</pre></details>').join('');}
el('mode').onchange=render;el('stage').onchange=render;render();</script></html>`;
}
module.exports = { report };
